### PR TITLE
feat: add RTL support + storybook

### PR DESCRIPTION
**Pull request by alireza-mh**
help to close this issue #17 
I didn't check it with all of the examples since some of them were irrelevant for RTL support and also I wanted to know this PR match with your conventions and roadmap of this component or not so I can progress further in case this looks ok to you.

Also added storybook for development purpose

### CODE REVIEW

**Comment by rcbyr** [comment]
Hello @alireza-mh 

thank you for your pull request. Sorry, for the late answer but I'm a little bit busy this month. Unfortunately, I couldn't get it working yet (all examples are broken when rtl is set to true). Did it work for you? 

Since the examples are more of a playground, I like the idea of using Codesandbox instead of Storybook, so that people can easily share problems etc.

I'm currently working on a complete rewrite of this project, and I'm already quite far along with that. Issue #17 and also #3 is already solved there. I'm not sure when I will release this version (I hope next month). If you make rtl work for all examples, I would love to merge your pull request and bring this function into the main version. (without storybook ;-))

**Comment by alireza-mh** [comment]
Thanks for your review I will check with other samples I have no idea why it may break on other samples.
I added a storybook only for development purposes only.
how do you debug your package? I thought it will make the development process easier.
I will remove the storybook from this commit

**Comment by rcbyr** [comment]
I will also have a look at it when I have time. At the moment I use a hidden repository with a playground and npm link. I will put the codeboxsandbox examples in this repository. Maybe at the weekend.

**Comment by rcbyr** [comment]
Hey @alireza-mh 

I added that feature with version 5.3.2. Thanks for your help.

**Pull request closed without merging**
